const val KOTLIN_VERSION = "1.6.0"
const val DOKKA_VERSION = "1.5.31"
const val AGP_VERSION = "7.0.3"
const val COROUTINES_VERSION = "1.5.2-native-mt"
const val GUAVA_VERSION = "27.0.1-android"
const val AWAITALITY_VERSION = "3.1.2"
const val ATOMICFU_VERSION = "0.17.0"