name: Docs

on:
  create:
    branches: [ main ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v1
      - uses: gradle/gradle-build-action@v2
        name: Publish (macos)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          arguments: clean dokkaHtmlMultiModule
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: build/dokka/htmlMultiModule
          SINGLE_COMMIT: true
